const CANVAS_WIDTH = 800;
const CANVAS_HEIGHT = 600;
const GRID_SIZE = 25;
const VERTICAL_ROWS = CANVAS_HEIGHT / GRID_SIZE;
const HORIZONTAL_ROWS = CANVAS_WIDTH / GRID_SIZE;

module.exports = {
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  GRID_SIZE,
  VERTICAL_ROWS,
  HORIZONTAL_ROWS,
};
