const CANVAS_WIDTH = 800;
const CANVAS_HEIGHT = 600;
const CANVAS_VERTICAL_CENTER = CANVAS_HEIGHT / 2;
const CANVAS_HORIZONTAL_CENTER = CANVAS_WIDTH / 2;
const GRID_SIZE = 32;
const VERTICAL_ROWS = CANVAS_HEIGHT / GRID_SIZE;
const HORIZONTAL_ROWS = CANVAS_WIDTH / GRID_SIZE;

const TEXT_ALIGN_LEFT = 'left';
const TEXT_ALIGN_CENTER = 'center';
const TEXT_ALIGN_RIGHT = 'right';

const ACTIONS = {
  BATTLE_STATIONS: 'To Battle Stations!',
  PERISCOPE_DEPTH: 'Periscope depth',
  EMERGENCY_DEPTH: 'Emergency depth',
  TURN_OFF_ENGINE: 'Turn off Engine',
  TURN_ON_ENGINE: 'Turn on Engine',
};

const SHIP_STATE = {
  MOVING: 'moving',
  ANCHOR: 'anchor',
  DIVING: 'diving',
  RESURFACING: 'resurfacing',
};

const SHIP_LEVEL = {
  ABOVE_WATER: 'above-water',
  BELOW_WATER: 'below-water',
};

const COLORS = {
  JET: { HEX: '#353535', RGB: [53, 53, 53] },
  MING: { HEX: '#3C6E71', RGB: [60, 110, 113] },
  WHITE: { HEX: '#FEFFED', RGB: [254, 255, 237] },
  BLACK: { HEX: '#000000', RGB: [0, 0, 0] },
  GAINSBORO: { HEX: '#D9D9D9', RGB: [217, 217, 217] },
  INDIGO_DYE: { HEX: '#284B63', RGB: [40, 74, 99] },
};

export {
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  CANVAS_VERTICAL_CENTER,
  CANVAS_HORIZONTAL_CENTER,
  GRID_SIZE,
  VERTICAL_ROWS,
  HORIZONTAL_ROWS,
  TEXT_ALIGN_LEFT,
  TEXT_ALIGN_CENTER,
  TEXT_ALIGN_RIGHT,
  ACTIONS,
  SHIP_STATE,
  SHIP_LEVEL,
  COLORS,
};
